//! FHIR R5 SubscriptionTopic Resource
//!
//! Auto-generated from FHIR schema definitions.
//! Do not modify directly.

use crate::r5::types::*;
use serde::{Deserialize, Serialize};

/// Definition of a resource-based trigger for the subscription topic
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SubscriptionTopicResourceTrigger {
    /// Unique id for inter-element referencing
    pub id: Option<String>,

    /// Additional content defined by implementations
    pub extension: Option<Vec<Extension>>,

    /// Extensions that cannot be ignored even if unrecognized
    #[serde(rename = "modifierExtension")]
    pub modifier_extension: Option<Vec<Extension>>,

    /// Text representation of the resource trigger
    pub description: Option<String>,

    /// Data Type or Resource (reference to definition) for this trigger definition
    pub resource: String,

    /// create | update | delete
    #[serde(rename = "supportedInteraction")]
    pub supported_interaction: Option<Vec<String>>,

    /// Query based trigger rule
    #[serde(rename = "queryCriteria")]
    pub query_criteria: Option<SubscriptionTopicResourceTriggerQueryCriteria>,

    /// FHIRPath based trigger rule
    #[serde(rename = "fhirPathCriteria")]
    pub fhir_path_criteria: Option<String>,
}

/// Query based trigger rule
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SubscriptionTopicResourceTriggerQueryCriteria {
    /// Unique id for inter-element referencing
    pub id: Option<String>,

    /// Additional content defined by implementations
    pub extension: Option<Vec<Extension>>,

    /// Extensions that cannot be ignored even if unrecognized
    #[serde(rename = "modifierExtension")]
    pub modifier_extension: Option<Vec<Extension>>,

    /// Rule applied to previous resource state
    pub previous: Option<String>,

    /// test-passes | test-fails
    #[serde(rename = "resultForCreate")]
    pub result_for_create: Option<String>,

    /// Rule applied to current resource state
    pub current: Option<String>,

    /// test-passes | test-fails
    #[serde(rename = "resultForDelete")]
    pub result_for_delete: Option<String>,

    /// Both must be true flag
    #[serde(rename = "requireBoth")]
    pub require_both: Option<bool>,
}

/// Event definitions the SubscriptionTopic
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SubscriptionTopicEventTrigger {
    /// Unique id for inter-element referencing
    pub id: Option<String>,

    /// Additional content defined by implementations
    pub extension: Option<Vec<Extension>>,

    /// Extensions that cannot be ignored even if unrecognized
    #[serde(rename = "modifierExtension")]
    pub modifier_extension: Option<Vec<Extension>>,

    /// Text representation of the event trigger
    pub description: Option<String>,

    /// Event which can trigger a notification from the SubscriptionTopic
    pub event: CodeableConcept,

    /// Data Type or Resource (reference to definition) for this trigger definition
    pub resource: String,
}

/// Properties by which a Subscription can filter notifications from the SubscriptionTopic
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SubscriptionTopicCanFilterBy {
    /// Unique id for inter-element referencing
    pub id: Option<String>,

    /// Additional content defined by implementations
    pub extension: Option<Vec<Extension>>,

    /// Extensions that cannot be ignored even if unrecognized
    #[serde(rename = "modifierExtension")]
    pub modifier_extension: Option<Vec<Extension>>,

    /// Description of this filter parameter
    pub description: Option<String>,

    /// URL of the triggering Resource that this filter applies to
    pub resource: Option<String>,

    /// Human-readable and computation-friendly name for a filter parameter usable by subscriptions on this topic, via Subscription.filterBy.filterParameter
    #[serde(rename = "filterParameter")]
    pub filter_parameter: String,

    /// Canonical URL for a filterParameter definition
    #[serde(rename = "filterDefinition")]
    pub filter_definition: Option<String>,

    /// eq | ne | gt | lt | ge | le | sa | eb | ap
    pub comparator: Option<Vec<String>>,

    /// missing | exact | contains | not | text | in | not-in | below | above | type | identifier | of-type | code-text | text-advanced | iterate
    pub modifier: Option<Vec<String>>,
}

/// Properties for describing the shape of notifications generated by this topic
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SubscriptionTopicNotificationShape {
    /// Unique id for inter-element referencing
    pub id: Option<String>,

    /// Additional content defined by implementations
    pub extension: Option<Vec<Extension>>,

    /// Extensions that cannot be ignored even if unrecognized
    #[serde(rename = "modifierExtension")]
    pub modifier_extension: Option<Vec<Extension>>,

    /// URL of the Resource that is the focus (main) resource in a notification shape
    pub resource: String,

    /// Include directives, rooted in the resource for this shape
    pub include: Option<Vec<String>>,

    /// Reverse include directives, rooted in the resource for this shape
    #[serde(rename = "revInclude")]
    pub rev_include: Option<Vec<String>>,
}

/// Describes a stream of resource state changes identified by trigger criteria and annotated with labels useful to filter projections from this topic.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SubscriptionTopic {
    /// The type of resource
    #[serde(rename = "resourceType")]
    pub resource_type: String,

    /// Logical id of this artifact
    pub id: Option<String>,

    /// Metadata about the resource
    pub meta: Option<Meta>,

    /// A set of rules under which this content was created
    #[serde(rename = "implicitRules")]
    pub implicit_rules: Option<String>,

    /// Language of the resource content
    pub language: Option<String>,

    /// Text summary of the resource, for human interpretation
    pub text: Option<Narrative>,

    /// Contained, inline Resources
    pub contained: Option<Vec<serde_json::Value>>,

    /// Additional content defined by implementations
    pub extension: Option<Vec<Extension>>,

    /// Extensions that cannot be ignored
    #[serde(rename = "modifierExtension")]
    pub modifier_extension: Option<Vec<Extension>>,

    /// Canonical identifier for this subscription topic, represented as an absolute URI (globally unique)
    pub url: String,

    /// Business identifier for subscription topic
    pub identifier: Option<Vec<Box<Identifier>>>,

    /// Business version of the subscription topic
    pub version: Option<String>,

    /// How to compare versions
    #[serde(rename = "versionAlgorithmString")]
    pub version_algorithm_string: Option<String>,

    #[serde(rename = "versionAlgorithmCoding")]
    pub version_algorithm_coding: Option<Coding>,

    /// Name for this subscription topic (computer friendly)
    pub name: Option<String>,

    /// Name for this subscription topic (human friendly)
    pub title: Option<String>,

    /// Based on FHIR protocol or definition
    #[serde(rename = "derivedFrom")]
    pub derived_from: Option<Vec<String>>,

    /// draft | active | retired | unknown
    pub status: String,

    /// If for testing purposes, not real usage
    pub experimental: Option<bool>,

    /// Date status first applied
    pub date: Option<String>,

    /// The name of the individual or organization that published the SubscriptionTopic
    pub publisher: Option<String>,

    /// Contact details for the publisher
    pub contact: Option<Vec<ContactDetail>>,

    /// Natural language description of the SubscriptionTopic
    pub description: Option<String>,

    /// Content intends to support these contexts
    #[serde(rename = "useContext")]
    pub use_context: Option<Vec<UsageContext>>,

    /// Intended jurisdiction of the SubscriptionTopic (if applicable)
    pub jurisdiction: Option<Vec<CodeableConcept>>,

    /// Why this SubscriptionTopic is defined
    pub purpose: Option<String>,

    /// Use and/or publishing restrictions
    pub copyright: Option<String>,

    /// Copyright holder and year(s)
    #[serde(rename = "copyrightLabel")]
    pub copyright_label: Option<String>,

    /// When SubscriptionTopic is/was approved by publisher
    #[serde(rename = "approvalDate")]
    pub approval_date: Option<String>,

    /// Date the Subscription Topic was last reviewed by the publisher
    #[serde(rename = "lastReviewDate")]
    pub last_review_date: Option<String>,

    /// The effective date range for the SubscriptionTopic
    #[serde(rename = "effectivePeriod")]
    pub effective_period: Option<Period>,

    /// Definition of a resource-based trigger for the subscription topic
    #[serde(rename = "resourceTrigger")]
    pub resource_trigger: Option<Vec<SubscriptionTopicResourceTrigger>>,

    /// Event definitions the SubscriptionTopic
    #[serde(rename = "eventTrigger")]
    pub event_trigger: Option<Vec<SubscriptionTopicEventTrigger>>,

    /// Properties by which a Subscription can filter notifications from the SubscriptionTopic
    #[serde(rename = "canFilterBy")]
    pub can_filter_by: Option<Vec<SubscriptionTopicCanFilterBy>>,

    /// Properties for describing the shape of notifications generated by this topic
    #[serde(rename = "notificationShape")]
    pub notification_shape: Option<Vec<SubscriptionTopicNotificationShape>>,
}
